### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'      

### ISSUE THREAD

**Issue by glenviewjeff** [hahnicity/scrapezillow#1]
Getting the error: AttributeError: 'NoneType' object has no attribute 'text'"

Does this tool require Python 3?  I'd love to use it.  Incidentally, when I tried installing on Windows, I got an import error that it couldn't find the urlparse module.  I got much further installing under Linux (the attribute error.)  Thanks!

./packages/python2/2.7.6/bin/scrapezillow --zpid 3364934                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                                                                        
  File "./packages/python2/2.7.6/bin/scrapezillow", line 9, in <module>                                                                                                                                                                   
    load_entry_point('scrapezillow==0.1', 'console_scripts', 'scrapezillow')()                                                                                                                                                            
  File "/home/action/.parts/packages/python2/2.7.6/lib/python2.7/site-packages/scrapezillow/main.py", line 14, in main                                                                                                                    
    pprint(scrape_url(**args.__dict__))                                                                                                                                                                                                   
  File "/home/action/.parts/packages/python2/2.7.6/lib/python2.7/site-packages/scrapezillow/scraper.py", line 115, in scrape_url                                                                                                          
    results = _get_property_summary(soup)                                                                                                                                                                                                 
  File "/home/action/.parts/packages/python2/2.7.6/lib/python2.7/site-packages/scrapezillow/scraper.py", line 36, in _get_property_summary                                                                                                
    prop_summary = soup.find("div", class_=constants.PROP_SUMMARY_CLASS).text                                                                                                                                                             
AttributeError: 'NoneType' object has no attribute 'text'                                                                                                                                                                                 
action@chrome-bullet-69-225043:~/.parts$

**Comment by hahnicity** [comment]
I'll check this out when I get home. 

I can guarantee that this should work with linux and python 2.7. I can make no guarantees for windows. That said I'll bet zillow changed their html and so my parser needs to be updated.

**Comment by glenviewjeff** [comment]
Thanks!

**Comment by hahnicity** [comment]
@glenviewjeff I investigated the issue and it should be fixed. If you pull the latest changes things should work just fine. I haven't released to pypi with the changes though. If that is a blocker for you I can test more and then do that.

**Comment by glenviewjeff** [comment]
I'm a Python novice; I could try to run from sources, but it would be easier for me if I can just install with pip.  Thanks!

**Comment by hahnicity** [comment]
Sure. Done

```
(scrapezillow0.2)greg@Ithilien:~/workspace/python/scrapezillow$ pip install scrapezillow
...
Successfully installed scrapezillow beautifulsoup4 requests
Cleaning up...

(scrapezillow0.2)greg@Ithilien:~/workspace/python/scrapezillow$ pip freeze
argparse==1.2.1
beautifulsoup4==4.3.2
requests==2.7.0
scrapezillow==0.2
wsgiref==0.1.2

(scrapezillow0.2)greg@Ithilien:~/workspace/python/scrapezillow$ scrapezillow --zpid 3364934
{'bathrooms': u'3.5',
 'bedrooms': u'5',
 'city': u'Wilmette',
 'description': u"Fantastic location steps to hot new downtown Wilmette restaurants and shops, walk to train and beach!! 5 bed 3.1 bath, hardwood floors throughout, all lux baths w/ natural stone, cherry, stainless granite kitchen with newer appliances, 2 wbfps, TONS of sunlight, outstanding master. 2nd floor laundry, full deep finished basement. HUGE yard. Don''t miss this!!",
 'price': u'1,099,000',
 'price_cut': u'66,000',
 'sqft': u'3,500',
 'state': u'IL',
 'status': u'For Sale',
 'zestimate': u'1,154,041',
 'zipcode': u'60091'}
```

**Comment by glenviewjeff** [comment]
Works like a charm now, thanks!  Took some extra time trying to figure out why it was failing on the urlparse module until I found out I needed to revert to Python2 :)
